[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# Compiler configuration
solc = '0.8.23'
optimizer = true
optimizer_runs = 200

# Test configuration
fuzz_runs = 256
ffi = true

# Deployment configuration
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan.sepolia]
key = "${ETHERSCAN_API_KEY}"

# Solidity remappings
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'cross-chain-swap/=lib/cross-chain-swap/',
    'solmate/=lib/solmate/',
    'openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/',
    'forge-std/=lib/forge-std/src/'
]
